//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseSection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int recordid { get; set; }
        public int workdayid { get; set; }
        public int userid { get; set; }
        public int numperson { get; set; }
    
        public virtual user user { get; set; }
        public virtual workday workday { get; set; }
    }
}
